AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Rails:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 120
