AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 120
