language: ruby
rvm: 2.6.1
cache: bundler
services:
  - postgresql
before_script:
  - psql -c 'create database universityguru_test;' -U postgres
  - bundle install
script:
  - ruby -v
  - gem -v
  - bundle -v
  - RAILS_ENV=test bundle exec rake test
  - bundle exec rubocop
